name: Environment Variables
on:
  push:
    branches: feature/global-env
env:
  GLOBAL_VAR: This is Global Variable
jobs:
  first-job:
    name: A Job
    runs-on: ubuntu-latest
    steps:
      - name: Output Global Variable
        run: echo "${GLOBAL_VAR}"
  second-job:
    name: Another Job
    runs-on: ubuntu-latest
    steps:
      - name: Output Global Variable
        run: echo "${GLOBAL_VAR}"